"""add credit_cards installments credit_card_bills tables

Revision ID: 0419cc11bf54
Revises: 69e49cf83b90
Create Date: 2026-03-15 01:36:44.034899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0419cc11bf54'
down_revision: Union[str, None] = '69e49cf83b90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('billing_day', sa.Integer(), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('credit_limit', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_card_bills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('credit_card_id', sa.Integer(), nullable=False),
    sa.Column('billing_year', sa.Integer(), nullable=False),
    sa.Column('billing_month', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('general_spending', sa.Integer(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_card_id', 'billing_year', 'billing_month', name='uq_card_year_month')
    )
    with op.batch_alter_table('credit_card_bills', schema=None) as batch_op:
        batch_op.create_index('ix_credit_card_bills_due_paid', ['due_date', 'is_paid'], unique=False)

    op.create_table('installments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('obligation_id', sa.Integer(), nullable=False),
    sa.Column('credit_card_id', sa.Integer(), nullable=False),
    sa.Column('installment_type', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('monthly_amount', sa.Integer(), nullable=False),
    sa.Column('total_periods', sa.Integer(), nullable=False),
    sa.Column('remaining_periods', sa.Integer(), nullable=False),
    sa.Column('interest_rate', sa.Numeric(), nullable=True),
    sa.Column('fee', sa.Integer(), nullable=True),
    sa.Column('current_period_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('installments', schema=None) as batch_op:
        batch_op.create_index('ix_installments_credit_card_period', ['credit_card_id', 'current_period_date'], unique=False)
        batch_op.create_index('ix_installments_obligation_id', ['obligation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installments', schema=None) as batch_op:
        batch_op.drop_index('ix_installments_obligation_id')
        batch_op.drop_index('ix_installments_credit_card_period')

    op.drop_table('installments')
    with op.batch_alter_table('credit_card_bills', schema=None) as batch_op:
        batch_op.drop_index('ix_credit_card_bills_due_paid')

    op.drop_table('credit_card_bills')
    op.drop_table('credit_cards')
    # ### end Alembic commands ###
